### ISSUE TITLE
Constraint Detection Add-on throws an errorHel

### ISSUE THREAD

**Issue by Sofiane-OUCHENE** [HAW-Process-Automation/Constraint-Detection#4]
Hello,

We are getting this error message with some workbooks when trying to use the Constraint Add-on: "_**RuntimeError: Due to a SPy issue the add-on can only be executed if you are the workbook owner.
            The owner of this workbook is John DOE.

Error found at line 2 in cell 2.**_"

Could you please help?

Best regards,
Sofiane

**Comment by Sofiane-OUCHENE** [comment]
Hello,

Any updates on this please?

Best regards,
Sofiane

**Comment by LeaTiedemann** [comment]
Hello, 
sorry for the late response. SPy is the Seeq Python library which is used in the code of the constraint detection add-on. There is an issue within SPy which makes it difficult to create/manipulate asset trees if you are not the workbook owner. Therefore, you can (unfortunately) only use the the add-on if you are working in a workbook that you created yourself. In this case, your colleague John seems to be the workbook owner and John has probably given you access to his workbook. I would recommend that you create a new workbook for yourself, so that you can use the add-on. I hope this helps you out!
Best regards,
Lea
